version: '3'

services:
  netcat_listener:
    container_name: netcat_listener
    restart: always 
    build: . 
    depends_on: 
      - nginx-server
    ports:
    - "8003:8003" 

  nginx-server:
    image: fabiocicerchia/nginx-lua
    container_name: my_nginx_server 
    depends_on:
      - my-http-server
    volumes:
      - ./nginx_log/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9000:9000"

  my-http-server:
    container_name: my_http_server 
    restart: always
    build: ./MyHttpServer
    ports:
      - "8080:8080"
